import json
from pathlib import Path

from harbor.core.l2 import L2Generator
from harbor.core.module_capsule import (
    compute_module_fingerprint,
    collect_module_context,
    generate_debug_playbook,
    generate_module_card,
    generate_review_checklist,
    module_capsule_dir,
    normalize_module_path,
    read_capsule_fingerprint,
    write_module_capsule,
)


def _write_sample_repo(tmp_path: Path) -> None:
    cfg = tmp_path / ".harbor" / "config" / "harbor.yaml"
    cfg.parent.mkdir(parents=True, exist_ok=True)
    cfg.write_text("code_roots:\n- harbor/**\n- tests/**\nexclude_paths: []\n", encoding="utf-8")

    pkg = tmp_path / "harbor" / "core"
    pkg.mkdir(parents=True, exist_ok=True)
    (pkg / "__init__.py").write_text("", encoding="utf-8")
    (pkg / "sample.py").write_text(
        '''def run(value: int) -> int:
    """Return the provided value.

    Behavior:
      - Returns the provided integer unchanged.

    Args:
      value (int): Input integer.

    Returns:
      int: Same integer value.

    @harbor.scope: public
    @harbor.l3_strictness: strict
    """
    return value
''',
        encoding="utf-8",
    )

    tests_dir = tmp_path / "tests"
    tests_dir.mkdir(parents=True, exist_ok=True)
    (tests_dir / "test_sample.py").write_text("def test_sample():\n    assert True\n", encoding="utf-8")


def _write_index(tmp_path: Path) -> Path:
    idx = tmp_path / ".harbor" / "cache" / "l3_index.json"
    idx.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "files": {
            "harbor/core/sync.py": {
                "items": [
                    {
                        "id": "harbor.core.sync.SyncEngine.check_status",
                        "qualified_name": "SyncEngine.check_status",
                        "scope": "public",
                        "strictness": "standard",
                    }
                ]
            },
            "harbor/core/l2.py": {
                "items": [
                    {
                        "id": "harbor.core.l2.L2Generator.generate",
                        "qualified_name": "L2Generator.generate",
                        "scope": "public",
                        "strictness": "standard",
                    }
                ]
            },
            "harbor/cli/main.py": {
                "items": [
                    {
                        "id": "harbor.cli.main.main",
                        "qualified_name": "main",
                        "scope": "public",
                        "strictness": "standard",
                    }
                ]
            },
        }
    }
    idx.write_text(json.dumps(payload), encoding="utf-8")
    return idx


def test_normalize_module_path_supports_windows_and_posix():
    assert normalize_module_path("harbor/core") == "harbor/core"
    assert normalize_module_path(r"harbor\core") == "harbor/core"
    assert normalize_module_path("//harbor//core//") == "harbor/core"


def test_module_capsule_dir_keeps_nested_path():
    p = module_capsule_dir(r"harbor\core")
    assert p.as_posix() == ".harbor/views/modules/harbor/core"


def test_collect_module_context_matches_prefix_only(tmp_path: Path):
    idx_path = _write_index(tmp_path)
    ctx = collect_module_context(r"harbor\core", index_path=idx_path)
    assert ctx["module"] == "harbor/core"
    assert ctx["key_files"] == ["harbor/core/l2.py", "harbor/core/sync.py"]
    symbols = [c["symbol"] for c in ctx["contracts"]]
    assert "L2Generator.generate" in symbols
    assert "SyncEngine.check_status" in symbols
    assert all(not fp.startswith("harbor/cli/") for fp in ctx["key_files"])


def test_generators_include_required_sections(tmp_path: Path, monkeypatch):
    idx_path = _write_index(tmp_path)
    proj_tests = tmp_path / "tests"
    proj_tests.mkdir(parents=True, exist_ok=True)
    (proj_tests / "test_sync_engine.py").write_text(
        "from harbor.core.sync import SyncEngine\n\n"
        "def test_sync_engine_status():\n"
        "    assert SyncEngine is not None\n",
        encoding="utf-8",
    )
    monkeypatch.chdir(tmp_path)

    ctx = collect_module_context("harbor/core", index_path=idx_path)
    module_card = generate_module_card(ctx)
    checklist = generate_review_checklist(ctx)
    playbook = generate_debug_playbook(ctx)

    assert "# Module Card: harbor/core" in module_card
    assert "This file is generated by Harbor-spec." in module_card
    assert "SyncEngine.check_status" in module_card
    assert "No test files detected by Harbor." not in module_card
    assert "## High-Risk Boundaries" in module_card
    assert "## Common Change Entry Points" in module_card
    assert "## Best Files To Inspect First" in module_card
    assert "## Relevant Tests" in module_card
    assert "This module appears to cover code under:" not in module_card

    assert "## Contract Checks" in checklist
    assert "## DDT / Test Checks" in checklist
    assert "## Runtime Safety Checks" in checklist
    assert "## Generated Context Checks" in checklist
    assert "## Module-Specific Focus" in checklist
    assert "## Semantic Drift Checks" in checklist
    assert "stale / doctor / verify-generated" in checklist

    assert "## First Files to Inspect" in playbook
    assert "## Workflow Entry Points" in playbook
    assert "Generated context / verify / stale / doctor" in playbook
    assert "## Why These Tests" in playbook
    assert "## Safe Fix Order" in playbook
    assert "## When to Escalate" in playbook
    assert "harbor/core/__init__.py" not in playbook
    assert "pytest tests/test_sync_engine.py" in playbook


def test_no_records_is_friendly(tmp_path: Path):
    idx_path = tmp_path / ".harbor" / "cache" / "l3_index.json"
    idx_path.parent.mkdir(parents=True, exist_ok=True)
    idx_path.write_text(json.dumps({"files": {}}), encoding="utf-8")

    ctx = collect_module_context("harbor/core", index_path=idx_path)
    assert ctx["key_files"] == []
    assert ctx["contracts"] == []
    card = generate_module_card(ctx)
    assert "No indexed contracts found for this module." in card


def test_debug_playbook_deprioritizes_init_and_prefers_workflow_files():
    ctx = {
        "module": "harbor/core",
        "key_files": [
            "harbor/core/__init__.py",
            "harbor/core/module_capsule.py",
            "harbor/core/l2.py",
            "harbor/core/sync.py",
        ],
        "contracts": [
            {
                "symbol": "SyncEngine.check_status",
                "file": "harbor/core/sync.py",
                "scope": "public",
                "strictness": "standard",
            }
        ],
        "tests": ["tests/test_sync_engine.py"],
        "strictness": "standard",
    }

    playbook = generate_debug_playbook(ctx)

    assert "harbor/core/__init__.py" not in playbook
    assert "harbor/core/module_capsule.py" in playbook
    assert "harbor/core/l2.py" in playbook
    assert "Workspace path / file write safety" in playbook


def test_review_checklist_highlights_typescript_preview_boundary():
    ctx = {
        "module": "harbor/adapters/typescript",
        "key_files": ["harbor/adapters/typescript/adapter.py"],
        "contracts": [],
        "tests": [],
        "strictness": "standard",
    }

    checklist = generate_review_checklist(ctx)

    assert "preview/advisory boundaries" in checklist
    assert "formal TypeScript DDT or semantic audit gate" in checklist


def test_debug_playbook_prioritizes_typescript_preview_workflow():
    ctx = {
        "module": "harbor/adapters/typescript",
        "key_files": [
            "harbor/adapters/typescript/adapter.py",
            "harbor/adapters/typescript/public_boundary.py",
            "harbor/adapters/typescript/parser.py",
        ],
        "contracts": [
            {
                "symbol": "harbor.adapters.typescript.public_boundary.describe_boundary",
                "file": "harbor/adapters/typescript/public_boundary.py",
                "scope": "public",
                "strictness": "strict",
            }
        ],
        "tests": [
            "tests/test_typescript_adapter_mvp.py",
            "tests/test_semantic_audit_preview.py",
        ],
        "strictness": "strict",
    }

    playbook = generate_debug_playbook(ctx)

    assert "TypeScript adapter / public boundary preview" in playbook
    assert "harbor/adapters/typescript/public_boundary.py" in playbook
    assert "tests/test_semantic_audit_preview.py" in playbook


def test_write_module_capsule_writes_three_files(tmp_path: Path):
    ctx = {
        "module": "harbor/core",
        "key_files": ["harbor/core/sync.py"],
        "contracts": [
            {
                "symbol": "SyncEngine.check_status",
                "file": "harbor/core/sync.py",
                "scope": "public",
                "strictness": "standard",
            }
        ],
        "tests": ["tests/test_sync_engine.py"],
        "strictness": "standard",
    }
    result = write_module_capsule(ctx, output_root=tmp_path / ".harbor" / "views" / "modules")
    written = result.canonical_paths
    names = [p.name for p in written]
    assert names == ["module-card.md", "review-checklist.md", "debug-playbook.md"]
    for p in written:
        assert p.exists()
        assert p.read_text(encoding="utf-8").startswith("---\n")
    assert result.exported_paths == []
    card = tmp_path / ".harbor" / "views" / "modules" / "harbor" / "core" / "module-card.md"
    card_text = card.read_text(encoding="utf-8")
    assert "fingerprint:" in card_text
    assert "view_fingerprint:" in card_text
    assert read_capsule_fingerprint(card) == compute_module_fingerprint(ctx)


def test_write_module_capsule_rejects_parent_traversal_module_path(tmp_path: Path):
    ctx = {
        "module": "../outside",
        "key_files": ["harbor/core/sync.py"],
        "contracts": [],
        "tests": [],
        "strictness": "standard",
    }
    try:
        write_module_capsule(ctx, output_root=tmp_path / ".harbor" / "views" / "modules")
        assert False, "expected traversal path validation to fail"
    except ValueError as ex:
        assert "Invalid module path" in str(ex)


def test_write_module_capsule_rejects_nested_parent_traversal_module_path(tmp_path: Path):
    ctx = {
        "module": "harbor/../../outside",
        "key_files": ["harbor/core/sync.py"],
        "contracts": [],
        "tests": [],
        "strictness": "standard",
    }
    try:
        write_module_capsule(ctx, output_root=tmp_path / ".harbor" / "views" / "modules")
        assert False, "expected traversal path validation to fail"
    except ValueError as ex:
        assert "Invalid module path" in str(ex)


def test_write_module_capsule_rejects_windows_absolute_module_path(tmp_path: Path):
    ctx = {
        "module": "C:/outside/project/module",
        "key_files": ["harbor/core/sync.py"],
        "contracts": [],
        "tests": [],
        "strictness": "standard",
    }
    try:
        write_module_capsule(ctx, output_root=tmp_path / ".harbor" / "views" / "modules")
        assert False, "expected Windows absolute module path validation to fail"
    except ValueError as ex:
        assert "Absolute paths are not allowed" in str(ex)


def test_write_module_capsule_rejects_export_root_outside_repo(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    cfg = tmp_path / ".harbor" / "config" / "harbor.yaml"
    cfg.parent.mkdir(parents=True, exist_ok=True)
    cfg.write_text("views:\n  export:\n    docs:\n      enabled: true\n      root: ../outside\n", encoding="utf-8")
    ctx = {
        "module": "harbor/core",
        "key_files": ["harbor/core/sync.py"],
        "contracts": [],
        "tests": [],
        "strictness": "standard",
    }
    try:
        write_module_capsule(ctx, root=tmp_path)
        assert False, "expected export root validation to fail"
    except ValueError as ex:
        assert "views.export.docs.root" in str(ex)


def test_write_module_capsule_rejects_windows_absolute_export_root(tmp_path: Path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    cfg = tmp_path / ".harbor" / "config" / "harbor.yaml"
    cfg.parent.mkdir(parents=True, exist_ok=True)
    cfg.write_text("views:\n  export:\n    docs:\n      enabled: true\n      root: C:/outside\n", encoding="utf-8")
    ctx = {
        "module": "harbor/core",
        "key_files": ["harbor/core/sync.py"],
        "contracts": [],
        "tests": [],
        "strictness": "standard",
    }
    try:
        write_module_capsule(ctx, root=tmp_path)
        assert False, "expected Windows absolute export root validation to fail"
    except ValueError as ex:
        assert "views.export.docs.root" in str(ex)


def test_collect_module_context_falls_back_to_transient_source_scan_without_cache(tmp_path: Path, monkeypatch):
    _write_sample_repo(tmp_path)
    monkeypatch.chdir(tmp_path)

    ctx = collect_module_context("harbor/core")

    assert ctx["module"] == "harbor/core"
    assert "harbor/core/__init__.py" in ctx["key_files"]
    assert "harbor/core/sample.py" in ctx["key_files"]
    assert any(contract["symbol"] == "harbor.core.sample.run" for contract in ctx["contracts"])
    assert ctx["strictness"] == "strict"
    assert not (tmp_path / ".harbor" / "cache" / "harbor.db").exists()


def test_l2_and_capsule_can_be_generated_without_runtime_index_cache(tmp_path: Path, monkeypatch):
    _write_sample_repo(tmp_path)
    monkeypatch.chdir(tmp_path)

    gen = L2Generator()
    markdown = gen.generate("harbor/core")
    written = gen.write("harbor/core", markdown, force=True)
    assert written is not None

    ctx = collect_module_context("harbor/core")
    result = write_module_capsule(ctx)

    assert any(path.name == "README.md" for path in written)
    assert any(path.name == "module-card.md" for path in result.canonical_paths)
    assert not (tmp_path / ".harbor" / "cache" / "l3_index.json").exists()
    assert not (tmp_path / ".harbor" / "cache" / "harbor.db").exists()
