import json
from pathlib import Path

from harbor.core.module_capsule import (
    compute_module_fingerprint,
    collect_module_context,
    generate_debug_playbook,
    generate_module_card,
    generate_review_checklist,
    module_capsule_dir,
    normalize_module_path,
    read_capsule_fingerprint,
    write_module_capsule,
)


def _write_index(tmp_path: Path) -> Path:
    idx = tmp_path / ".harbor" / "cache" / "l3_index.json"
    idx.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "files": {
            "harbor/core/sync.py": {
                "items": [
                    {
                        "id": "harbor.core.sync.SyncEngine.check_status",
                        "qualified_name": "SyncEngine.check_status",
                        "scope": "public",
                        "strictness": "standard",
                    }
                ]
            },
            "harbor/core/l2.py": {
                "items": [
                    {
                        "id": "harbor.core.l2.L2Generator.generate",
                        "qualified_name": "L2Generator.generate",
                        "scope": "public",
                        "strictness": "standard",
                    }
                ]
            },
            "harbor/cli/main.py": {
                "items": [
                    {
                        "id": "harbor.cli.main.main",
                        "qualified_name": "main",
                        "scope": "public",
                        "strictness": "standard",
                    }
                ]
            },
        }
    }
    idx.write_text(json.dumps(payload), encoding="utf-8")
    return idx


def test_normalize_module_path_supports_windows_and_posix():
    assert normalize_module_path("harbor/core") == "harbor/core"
    assert normalize_module_path(r"harbor\core") == "harbor/core"
    assert normalize_module_path("//harbor//core//") == "harbor/core"


def test_module_capsule_dir_keeps_nested_path():
    p = module_capsule_dir(r"harbor\core")
    assert p.as_posix() == "docs/harbor/modules/harbor/core"


def test_collect_module_context_matches_prefix_only(tmp_path: Path):
    idx_path = _write_index(tmp_path)
    ctx = collect_module_context(r"harbor\core", index_path=idx_path)
    assert ctx["module"] == "harbor/core"
    assert ctx["key_files"] == ["harbor/core/l2.py", "harbor/core/sync.py"]
    symbols = [c["symbol"] for c in ctx["contracts"]]
    assert "L2Generator.generate" in symbols
    assert "SyncEngine.check_status" in symbols
    assert all(not fp.startswith("harbor/cli/") for fp in ctx["key_files"])


def test_generators_include_required_sections(tmp_path: Path, monkeypatch):
    idx_path = _write_index(tmp_path)
    proj_tests = tmp_path / "tests"
    proj_tests.mkdir(parents=True, exist_ok=True)
    (proj_tests / "test_sync_engine.py").write_text("def test_sync_engine():\n    pass\n", encoding="utf-8")
    monkeypatch.chdir(tmp_path)

    ctx = collect_module_context("harbor/core", index_path=idx_path)
    module_card = generate_module_card(ctx)
    checklist = generate_review_checklist(ctx)
    playbook = generate_debug_playbook(ctx)

    assert "# Module Card: harbor/core" in module_card
    assert "This file is generated by Harbor-spec." in module_card
    assert "SyncEngine.check_status" in module_card
    assert "No test files detected by Harbor." not in module_card

    assert "## Contract Checks" in checklist
    assert "## DDT / Test Checks" in checklist
    assert "## Runtime Safety Checks" in checklist
    assert "## Semantic Drift Checks" in checklist

    assert "## First Files to Inspect" in playbook
    assert "## Safe Fix Order" in playbook
    assert "## When to Escalate" in playbook


def test_no_records_is_friendly(tmp_path: Path):
    idx_path = tmp_path / ".harbor" / "cache" / "l3_index.json"
    idx_path.parent.mkdir(parents=True, exist_ok=True)
    idx_path.write_text(json.dumps({"files": {}}), encoding="utf-8")

    ctx = collect_module_context("harbor/core", index_path=idx_path)
    assert ctx["key_files"] == []
    assert ctx["contracts"] == []
    card = generate_module_card(ctx)
    assert "No indexed contracts found for this module." in card


def test_write_module_capsule_writes_three_files(tmp_path: Path):
    ctx = {
        "module": "harbor/core",
        "key_files": ["harbor/core/sync.py"],
        "contracts": [
            {
                "symbol": "SyncEngine.check_status",
                "file": "harbor/core/sync.py",
                "scope": "public",
                "strictness": "standard",
            }
        ],
        "tests": ["tests/test_sync_engine.py"],
        "strictness": "standard",
    }
    written = write_module_capsule(ctx, output_root=tmp_path / "docs" / "harbor" / "modules")
    names = [p.name for p in written]
    assert names == ["module-card.md", "review-checklist.md", "debug-playbook.md"]
    for p in written:
        assert p.exists()
    card = tmp_path / "docs" / "harbor" / "modules" / "harbor" / "core" / "module-card.md"
    card_text = card.read_text(encoding="utf-8")
    assert card_text.startswith("---\n")
    assert "fingerprint:" in card_text
    assert read_capsule_fingerprint(card) == compute_module_fingerprint(ctx)
