from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Optional

from harbor.core.storage import HarborDB


def normalize_module_path(module: str) -> str:
    raw = (module or "").strip().replace("\\", "/")
    while "//" in raw:
        raw = raw.replace("//", "/")
    return raw.strip("/")


def module_capsule_dir(module: str, output_root: Optional[Path] = None) -> Path:
    root = output_root or (Path("docs") / "harbor" / "modules")
    normalized = normalize_module_path(module)
    return root / normalized


def _sort_unique(values: List[str]) -> List[str]:
    return sorted({v for v in values if v})


def _strictness_rank(value: str) -> int:
    mapping = {"light": 1, "standard": 2, "strict": 3}
    return mapping.get((value or "standard").lower(), 2)


def _summarize_strictness(contracts: List[Dict[str, str]]) -> str:
    if not contracts:
        return "standard"
    top = max(_strictness_rank(c.get("strictness", "standard")) for c in contracts)
    if top >= 3:
        return "strict"
    if top <= 1:
        return "light"
    return "standard"


def _load_index(index_path: Optional[Path] = None) -> Dict[str, Any]:
    idx_path = index_path or (Path(".harbor") / "cache" / "l3_index.json")
    if idx_path.exists():
        try:
            return json.loads(idx_path.read_text(encoding="utf-8"))
        except Exception:
            return {"files": {}}

    db = HarborDB()
    files: Dict[str, Any] = {}
    for fp, mtime in db.get_all_files():
        items = []
        for it in db.get_file_entries(fp):
            meta = it.get("meta", {}) or {}
            items.append(
                {
                    "id": it.get("id"),
                    "qualified_name": meta.get("qualified_name"),
                    "name": meta.get("name"),
                    "scope": meta.get("scope"),
                    "strictness": meta.get("strictness"),
                }
            )
        files[fp] = {"mtime": mtime, "items": items}
    return {"files": files}


def _belongs_to_module(file_path: str, module: str) -> bool:
    rel = (file_path or "").replace("\\", "/").strip("/")
    if not rel or not module:
        return False
    return rel == module or rel.startswith(f"{module}/")


def detect_tests_for_module(module: str, key_files: List[str], tests_root: Optional[Path] = None) -> List[str]:
    root = tests_root or Path("tests")
    if not root.exists():
        return []

    module_name = module.split("/")[-1] if module else ""
    keywords = {module_name} if module_name else set()
    for fp in key_files:
        stem = Path(fp).stem
        if stem:
            keywords.add(stem)

    matches: List[str] = []
    for test_file in root.rglob("test_*.py"):
        rel = test_file.as_posix()
        name = test_file.stem.lower()
        if any(kw and kw.lower() in name for kw in keywords):
            matches.append(rel)
    return _sort_unique(matches)


def collect_module_context(module: str, index_path: Optional[Path] = None) -> Dict[str, Any]:
    normalized = normalize_module_path(module)
    idx = _load_index(index_path=index_path)
    key_files: List[str] = []
    contracts: List[Dict[str, str]] = []

    for fp, meta in (idx.get("files") or {}).items():
        rel = (str(fp) or "").replace("\\", "/").strip("/")
        if not _belongs_to_module(rel, normalized):
            continue
        key_files.append(rel)
        for item in meta.get("items", []) or []:
            symbol = item.get("qualified_name") or item.get("id") or item.get("name") or ""
            contracts.append(
                {
                    "symbol": str(symbol),
                    "file": rel,
                    "scope": str(item.get("scope") or "unknown"),
                    "strictness": str(item.get("strictness") or "standard"),
                }
            )

    key_files = _sort_unique(key_files)
    contracts = sorted(
        [c for c in contracts if c.get("symbol")],
        key=lambda x: (x.get("symbol", ""), x.get("file", "")),
    )
    tests = detect_tests_for_module(normalized, key_files)
    return {
        "module": normalized,
        "key_files": key_files,
        "contracts": contracts,
        "tests": tests,
        "strictness": _summarize_strictness(contracts),
    }


def generate_module_card(context: Dict[str, Any]) -> str:
    module = context.get("module", "")
    key_files = context.get("key_files", []) or []
    contracts = context.get("contracts", []) or []
    tests = context.get("tests", []) or []
    debug_entries = key_files[:2]

    lines: List[str] = [
        f"# Module Card: {module}",
        "",
        "> This file is generated by Harbor-spec.",
        "> It is a derived maintenance view, not a source of truth.",
        "",
        "## Responsibility",
        "",
        "This module appears to cover code under:",
        "",
        "```text",
        module or "(unknown module)",
        "```",
        "",
        "If this summary is too generic, update the underlying contracts or module documentation rather than treating this file as the source of truth.",
        "",
        "## Key Files",
        "",
        "```text",
    ]
    if key_files:
        lines.extend(key_files)
    else:
        lines.append("No indexed files found for this module.")
    lines.extend(
        [
            "```",
            "",
            "## Public / Indexed Contracts",
            "",
        ]
    )
    if contracts:
        lines.extend(
            [
                "| Symbol | File | Scope | Strictness |",
                "| ------ | ---- | ----- | ---------- |",
            ]
        )
        for c in contracts:
            lines.append(
                f"| {c.get('symbol','')} | {c.get('file','')} | {c.get('scope','unknown')} | {c.get('strictness','standard')} |"
            )
    else:
        lines.extend(["```text", "No indexed contracts found for this module.", "```"])

    lines.extend(["", "## Tests", "", "```text"])
    if tests:
        lines.extend(tests)
    else:
        lines.append("No test files detected by Harbor.")

    lines.extend(
        [
            "```",
            "",
            "## Review Focus",
            "",
            "* Check Contract Impact before changing public behavior.",
            "* Check schema/type drift if this module exposes data structures.",
            "* Check DDT/test coverage for strict targets.",
            "* Check Runtime Safety if this module writes files, changes data, or touches external systems.",
            "",
            "## Debug Entry Points",
            "",
            "Start with:",
            "",
            "```text",
        ]
    )
    if debug_entries:
        lines.extend(debug_entries)
    else:
        lines.append(module or "(unknown module)")

    lines.extend(
        [
            "```",
            "",
            "## Related Views",
            "",
            "```text",
            "L2 README:",
            f"  {module}/README.md",
            "",
            "Capsule files:",
            f"  docs/harbor/modules/{module}/review-checklist.md",
            f"  docs/harbor/modules/{module}/debug-playbook.md",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def generate_review_checklist(context: Dict[str, Any]) -> str:
    module = context.get("module", "")
    return "\n".join(
        [
            f"# Review Checklist: {module}",
            "",
            "> This file is generated by Harbor-spec.",
            "> It helps AI coding assistants review this module without loading the whole repository.",
            "",
            "## Contract Checks",
            "",
            "- Did behavior, args, returns, raises, schema, side effects, state, idempotency, security, or external-visible result change?",
            "- If yes, update the relevant Contract before or together with implementation.",
            "- If no, state `Contract Impact: none`.",
            "",
            "## Schema / Type Checks",
            "",
            "- Check Pydantic models, OpenAPI, TypeScript types, event schemas, or database migrations if this module touches them.",
            "- Mark `[Contract Conflict]` if schema and docstring disagree.",
            "",
            "## DDT / Test Checks",
            "",
            "- Strict targets must use explicit `l3_version`.",
            '- Do not use `strategy="latest"` for strict targets.',
            "- Add or update tests for args boundary, returns, raises, side effects, and failure paths.",
            "",
            "## Runtime Safety Checks",
            "",
            "Ask before:",
            "",
            "- deleting files",
            "- changing migrations",
            "- changing CI/CD",
            "- touching secrets",
            "- installing dependencies",
            "- changing production config",
            "- modifying auth, permission, billing, or user data handling",
            "",
            "## Semantic Drift Checks",
            "",
            "Mark:",
            "",
            "```text",
            "[Possible Semantic Drift]",
            "```",
            "",
            "when implementation and contract may disagree.",
            "",
            "Mark:",
            "",
            "```text",
            "[Confirmed Semantic Drift]",
            "```",
            "",
            "when implementation definitely contradicts contract.",
            "",
            "## Final Review Output",
            "",
            "Use:",
            "",
            "```text",
            "Change Summary:",
            "Contract Impact:",
            "Strictness:",
            "Tests / DDT:",
            "Semantic Drift:",
            "Runtime Safety:",
            "Diary Draft:",
            "```",
            "",
        ]
    )


def generate_debug_playbook(context: Dict[str, Any]) -> str:
    module = context.get("module", "")
    key_files = context.get("key_files", []) or []
    tests = context.get("tests", []) or []

    lines = [
        f"# Debug Playbook: {module}",
        "",
        "> This file is generated by Harbor-spec.",
        "> It is a derived debug guide, not a source of truth.",
        "",
        "## First Files to Inspect",
        "",
        "```text",
    ]
    if key_files:
        lines.extend(key_files[:2])
    else:
        lines.append(module or "(unknown module)")
    lines.extend(["```", "", "## Minimal Checks", "", "Run targeted tests first if available.", ""])

    if tests:
        lines.extend(["```powershell", f"pytest {tests[0]}", "```"])
    else:
        lines.extend(
            [
                "```text",
                "No module-specific test command detected. Use project-level test commands from Project Rules.",
                "```",
            ]
        )

    lines.extend(
        [
            "",
            "## Common Debug Questions",
            "",
            "* What changed since the last passing state?",
            "* Did Contract Impact occur?",
            "* Did schema/type shape change?",
            "* Did a strict target lose DDT coverage?",
            "* Did implementation drift from docstring or schema?",
            "* Did path normalization or platform-specific behavior change?",
            "* Did the fix require a regression test?",
            "",
            "## Safe Fix Order",
            "",
            "1. Reproduce the issue.",
            "2. Identify relevant contract and schema.",
            "3. Add or update failing test if possible.",
            "4. Fix implementation.",
            "5. Re-run targeted tests.",
            "6. Check semantic drift.",
            "7. Draft Diary entry if the fix is important.",
            "",
            "## When to Escalate",
            "",
            "Escalate to full Harbor workflow if the fix touches:",
            "",
            "* public API",
            "* schema",
            "* parser/export/writeback",
            "* workflow",
            "* migration",
            "* security",
            "* user-visible behavior",
            "",
        ]
    )
    return "\n".join(lines)


def preview_module_capsule(context: Dict[str, Any]) -> Dict[str, str]:
    return {
        "module-card.md": generate_module_card(context),
        "review-checklist.md": generate_review_checklist(context),
        "debug-playbook.md": generate_debug_playbook(context),
    }


def write_module_capsule(context: Dict[str, Any], output_root: Optional[Path] = None) -> List[Path]:
    target_dir = module_capsule_dir(context.get("module", ""), output_root=output_root)
    target_dir.mkdir(parents=True, exist_ok=True)
    previews = preview_module_capsule(context)
    written: List[Path] = []
    for name in ["module-card.md", "review-checklist.md", "debug-playbook.md"]:
        path = target_dir / name
        path.write_text(previews[name], encoding="utf-8")
        written.append(path)
    return written
