from __future__ import annotations

import re
from pathlib import Path
from typing import Any, Dict, Optional

from harbor.core.module_capsule import (
    check_module_capsule_stale,
    module_capsule_dir,
    normalize_module_path,
)


def normalize_skill_slug(module: str) -> str:
    normalized = normalize_module_path(module).lower().replace("/", "-").replace("\\", "-")
    normalized = re.sub(r"[^a-z0-9-]+", "-", normalized)
    normalized = re.sub(r"-{2,}", "-", normalized).strip("-")
    return normalized


def skill_dir_for_module(module: str, root: Optional[Path] = None) -> Path:
    base = root or (Path(".agents") / "skills")
    slug = normalize_skill_slug(module)
    return base / f"harbor-debug-{slug}"


def check_capsule_ready_for_skill(
    module: str,
    output_root: Optional[Path] = None,
    context: Optional[Dict[str, Any]] = None,
) -> Dict[str, str]:
    module_name = normalize_module_path(module)
    ctx = context or {}
    key_files = ctx.get("key_files") or []
    contracts = ctx.get("contracts") or []
    if not key_files and not contracts:
        return {
            "status": "unknown_module",
            "module": module_name,
            "reason": "no indexed records found for module",
        }

    cap_dir = module_capsule_dir(module_name, output_root=output_root)
    required = ["module-card.md", "review-checklist.md", "debug-playbook.md"]
    missing = [name for name in required if not (cap_dir / name).exists()]
    if missing:
        return {
            "status": "missing_capsule",
            "module": module_name,
            "reason": "missing capsule files",
        }

    stale = check_module_capsule_stale(ctx, output_root=output_root)
    if stale.get("status") != "up_to_date":
        return {
            "status": "stale_capsule",
            "module": module_name,
            "reason": str(stale.get("reason") or "capsule is stale"),
        }
    return {
        "status": "ok",
        "module": module_name,
        "reason": "ready",
    }


def generate_module_skill(module: str) -> str:
    module_name = normalize_module_path(module)
    module_slug = normalize_skill_slug(module_name)
    return "\n".join(
        [
            "---",
            f"name: harbor-debug-{module_slug}",
            (
                f"description: Use when debugging, reviewing, or refactoring the {module_name} module. "
                "It routes the agent to the module capsule instead of loading the whole repository."
            ),
            "---",
            "",
            f"# Harbor Debug Skill: {module_name}",
            "",
            "This skill is a thin routing entrypoint generated by Harbor-spec.",
            "",
            "It does not replace source code, contracts, tests, or Module Capsule files.",
            "",
            "## When to use",
            "",
            "Use this skill when the task involves:",
            "",
            f"- debugging the `{module_name}` module",
            f"- reviewing changes in the `{module_name}` module",
            f"- refactoring the `{module_name}` module",
            f"- checking semantic drift in the `{module_name}` module",
            "- checking stale or missing module capsule context",
            "",
            "## Load order",
            "",
            f"1. Read `docs/harbor/modules/{module_name}/module-card.md`",
            f"2. If reviewing code, read `docs/harbor/modules/{module_name}/review-checklist.md`",
            f"3. If debugging failure, read `docs/harbor/modules/{module_name}/debug-playbook.md`",
            "4. Then inspect only the relevant source files listed in the module card.",
            "",
            "## Required checks",
            "",
            "- Contract Impact",
            "- Strictness",
            "- Tests / DDT",
            "- Semantic Drift",
            "- Runtime Safety",
            "- Diary Draft if behavior, schema, or user-visible results change",
            "",
            "## Before editing",
            "",
            "Run or suggest:",
            "",
            "```powershell",
            f"harbor module stale {module_name}",
            "```",
            "",
            "If stale, suggest:",
            "",
            "```powershell",
            f"harbor module seal {module_name} --write",
            "```",
            "",
            "## Do not",
            "",
            "- Do not treat this Skill as the source of truth.",
            "- Do not copy stale capsule content into code.",
            "- Do not read the whole repository unless the capsule points to insufficient context.",
            "- Do not modify contracts without checking tests / DDT.",
            "- Do not claim commands were run unless actually executed.",
            "",
        ]
    )


def write_module_skill(module: str, root: Optional[Path] = None) -> Path:
    target_dir = skill_dir_for_module(module, root=root)
    target_dir.mkdir(parents=True, exist_ok=True)
    target = target_dir / "SKILL.md"
    target.write_text(generate_module_skill(module), encoding="utf-8")
    return target
